// app/layout.tsx
import PasswordProtect from "@/components/PasswordProtect";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <PasswordProtect>{children}</PasswordProtect>
      </body>
    </html>
  );
}